# Generated by Django 2.2.6 on 2019-10-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20191027_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='site',
            field=models.CharField(choices=[('AMAZON', 'Item will be shipped by us'), ('FULFILLED', 'Item will be fulfilled by Amazon'), ('BAY', 'Ebay'), ('STOCK', 'Stock X'), ('GOAT', 'As stated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='site',
            field=models.CharField(choices=[('AMAZON', 'Item will be shipped by us'), ('FULFILLED', 'Item will be fulfilled by Amazon'), ('BAY', 'Ebay'), ('STOCK', 'Stock X'), ('GOAT', 'As stated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='website',
            name='site',
            field=models.CharField(choices=[('AMAZON', 'Item will be shipped by us'), ('FULFILLED', 'Item will be fulfilled by Amazon'), ('BAY', 'Ebay'), ('STOCK', 'Stock X'), ('GOAT', 'As stated')], max_length=50),
        ),
    ]
