# Generated by Django 2.2.6 on 2019-10-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20191027_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('item', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('site', models.CharField(choices=[('AMAZON', 'Amazon'), ('FULFILLED', 'FBA'), ('BAY', 'Ebay'), ('STOCK', 'Stock X'), ('GOAT', 'GOAT')], max_length=100)),
                ('purchased_price', models.FloatField()),
                ('posted_date', models.CharField(max_length=100)),
                ('bought_at', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('apparel_size', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('item', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('site', models.CharField(choices=[('AMAZON', 'Amazon'), ('FULFILLED', 'FBA'), ('BAY', 'Ebay'), ('STOCK', 'Stock X'), ('GOAT', 'GOAT')], max_length=100)),
                ('purchased_price', models.FloatField()),
                ('posted_date', models.CharField(max_length=100)),
                ('bought_at', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('item', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('site', models.CharField(choices=[('AMAZON', 'Amazon'), ('FULFILLED', 'FBA'), ('BAY', 'Ebay'), ('STOCK', 'Stock X'), ('GOAT', 'GOAT')], max_length=100)),
                ('purchased_price', models.FloatField()),
                ('posted_date', models.CharField(max_length=100)),
                ('bought_at', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('item', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('site', models.CharField(choices=[('AMAZON', 'Amazon'), ('FULFILLED', 'FBA'), ('BAY', 'Ebay'), ('STOCK', 'Stock X'), ('GOAT', 'GOAT')], max_length=100)),
                ('purchased_price', models.FloatField()),
                ('posted_date', models.CharField(max_length=100)),
                ('bought_at', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('shoe_size', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('item', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('site', models.CharField(choices=[('AMAZON', 'Amazon'), ('FULFILLED', 'FBA'), ('BAY', 'Ebay'), ('STOCK', 'Stock X'), ('GOAT', 'GOAT')], max_length=100)),
                ('purchased_price', models.FloatField()),
                ('posted_date', models.CharField(max_length=100)),
                ('bought_at', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
