# Generated by Django 2.2.6 on 2019-10-29 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20191028_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apparel',
            name='apparel_size',
        ),
    ]
